local: fix duration format (#728)
It should be an `int` according to `SongModel`'s spec, but not converted accordingly. Breaks pydantic validation:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for SongModel
duration
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=226533.87755102038, input_type=float]
```