[fix](reader): make reader thread safe
'播放全部' may fail due to
```
[2024-11-16 21:49:48,867 feeluown.task:85] [ERROR]: Task play-all failed
Traceback (most recent call last):
  File "/Users/xxx/code/feeluown/feeluown/task.py", line 81, in _cb
    future.result()
  File "/Users/xxx/code/feeluown/.venv/lib/python3.11/site-packages/qasync/__init__.py", line 150, in run
    r = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/code/feeluown/feeluown/utils/reader.py", line 173, in readall
    list(self)
  File "/Users/xxx/code/feeluown/feeluown/utils/reader.py", line 98, in __next__
    return self._read_next()
           ^^^^^^^^^^^^^^^^^
  File "/Users/xxx/code/feeluown/feeluown/utils/reader.py", line 192, in _read_next
    obj = next(self._g)
          ^^^^^^^^^^^^^
ValueError: generator already executing
[2024-11-16 21:49:48,871 qasync._QEventLoop:739] [ERROR]: Task exception was never retrieved
future: <Task finished name='Task-88455' coro=<TableContainer.play_all() done, defined at /Users/xxx/code/feeluown/feeluown/gui/page_containers/table
.py:420> exception=ValueError('generator already executing')>
Traceback (most recent call last):
  File "/Users/xxx/code/feeluown/feeluown/gui/page_containers/table.py", line 432, in play_all
    songs = await task_spec.bind_blocking_io(reader.readall)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: generator already executing
```