Fix goto() with only path
The warning suggests to use path instead of uri, but if only path is specified (without a query), the following exception would be raised:

```
  File "/usr/lib/python3.8/site-packages/feeluown/browser.py", line 54, in goto
    self._goto(model, uri)
  File "/usr/lib/python3.8/site-packages/feeluown/browser.py", line 88, in _goto
    model = resolve(uri)
  File "/usr/lib/python3.8/site-packages/fuocore/models/uri.py", line 145, in resolve
    model, path = parse_line(line)
  File "/usr/lib/python3.8/site-packages/fuocore/models/uri.py", line 110, in parse_line
    line = line.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

This change fixes this behavior, and also updated the docstring accordingly.